// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADDUO0gNbfS79T7lX9b2Zon_pQndhKZB8',
    appId: '1:5076005778:web:3c4f12b398911252b1874b',
    messagingSenderId: '5076005778',
    projectId: 'ai-reels-e7b81',
    authDomain: 'ai-reels-e7b81.firebaseapp.com',
    storageBucket: 'ai-reels-e7b81.firebasestorage.app',
    measurementId: 'G-HPK9DRNYGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWmDGtJbRLjI-IL1YxNWm88N-3BeqUQec',
    appId: '1:5076005778:android:37f227a2b034a3a8b1874b',
    messagingSenderId: '5076005778',
    projectId: 'ai-reels-e7b81',
    storageBucket: 'ai-reels-e7b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZB0WKIUS6Fw6iPYhrpa8-uv7FC2-cHmo',
    appId: '1:5076005778:ios:3ead8938b0bca548b1874b',
    messagingSenderId: '5076005778',
    projectId: 'ai-reels-e7b81',
    storageBucket: 'ai-reels-e7b81.firebasestorage.app',
    iosBundleId: 'com.hasretozkan.aiReels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZB0WKIUS6Fw6iPYhrpa8-uv7FC2-cHmo',
    appId: '1:5076005778:ios:3ead8938b0bca548b1874b',
    messagingSenderId: '5076005778',
    projectId: 'ai-reels-e7b81',
    storageBucket: 'ai-reels-e7b81.firebasestorage.app',
    iosBundleId: 'com.hasretozkan.aiReels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADDUO0gNbfS79T7lX9b2Zon_pQndhKZB8',
    appId: '1:5076005778:web:e009c03c221df1d4b1874b',
    messagingSenderId: '5076005778',
    projectId: 'ai-reels-e7b81',
    authDomain: 'ai-reels-e7b81.firebaseapp.com',
    storageBucket: 'ai-reels-e7b81.firebasestorage.app',
    measurementId: 'G-2D487PBYWX',
  );
}
